project:
  type: website
  render: 
    - "*.qmd"          # start broad…
    - "!EXAMPLE/**"   # …then exclude a folder  resources:
  resources: 
    - assets/avatar.jpg
    - assets/BACKGROUND.png
    - assets/cv/Wassim_Kabalan_CV.pdf

website:
  title: "Wassim Kabalan"
  site-url: https://askabalan.github.io
  description: "My personal website showcasing research in computational cosmology, publications, and projects in differentiable simulations and HPC."
  open-graph:
    locale: en_US
  navbar:
    right:
      - text: "Home"
        href: index.qmd
      - text: "Papers"
        href: papers
      - text: "CV"
        href: cv

format:
  html:
    theme: [sandstone]
    css: assets/styles.css
