---
title: Publications
page-layout: full
---


# 2026

- **Kabalan, W.**, Lanusse, F., Boucaud, A., and Aubourg, E. 2026. JAXPM: A JAX-Based Framework for Scalable and Differentiable Particle Mesh Simulations. In preparation.

- **Kabalan, W.**, Rizzieri, A., Sohn, W., Beringue, B., Basyrov, A., Chanial, P., Boucaud, A., and Errard, J. 2026. [A novel approach to optimize clustering for parametric map-based component separation for upcoming CMB polarization satellites](https://arxiv.org/abs/2604.08463). arXiv:2604.08463 [astro-ph.CO].

# 2025

- **Kabalan, W.**, Lanusse, F., Boucaud, A., and Aubourg, E. 2025. jaxDecomp: JAX Library for 3D Domain Decomposition and Parallel FFTs. Submitted to JOSS.

# 2024

- Spagnoletti, A., Boucaud, A., Huertas-Company, M., **Kabalan, W.**, and Biswas, B. 2024. [Bayesian Deconvolution of Astronomical Images with Diffusion Models: Quantifying Prior-Driven Features in Reconstructions](https://arxiv.org/abs/2411.19158). arXiv:2411.19158 [astro-ph.IM].

- Sommer, K., **Kabalan, W.**, and Brunet, R. 2024. [Infrared Radiometric Image Classification and Segmentation of Cloud Structure Using Deep-learning Framework for Ground-based Infrared Thermal Camera Observations](https://egusphere.copernicus.org/preprints/2024/egusphere-2024-101/). EGUsphere Preprint 2024-101. https://doi.org/10.5194/egusphere-2024-101.
